CREATE TABLE public.website (
                                id serial NOT NULL,
                                "name" varchar NOT NULL,
                                "domain" varchar NULL,
                                company_id int4 NOT NULL,
                                default_lang_id int4 NOT NULL,
                                auto_redirect_lang bool NULL,
                                cookies_bar bool NULL,
                                social_twitter varchar NULL,
                                social_facebook varchar NULL,
                                social_github varchar NULL,
                                social_linkedin varchar NULL,
                                social_youtube varchar NULL,
                                social_instagram varchar NULL,
                                has_social_default_image bool NULL,
                                google_analytics_key varchar NULL,
                                google_management_client_id varchar NULL,
                                google_management_client_secret varchar NULL,
                                google_search_console varchar NULL,
                                google_maps_api_key varchar NULL,
                                user_id int4 NOT NULL,
                                cdn_activated bool NULL,
                                cdn_url varchar NULL,
                                cdn_filters text NULL,
                                homepage_id int4 NULL,
                                custom_code_head text NULL,
                                custom_code_footer text NULL,
                                robots_txt text NULL,
                                theme_id int4 NULL,
                                specific_user_account bool NULL,
                                auth_signup_uninvited varchar NULL,
                                create_uid int4 NULL,
                                create_date timestamp NULL,
                                write_uid int4 NULL,
                                write_date timestamp NULL,
                                channel_id int4 NULL,
                                crm_default_team_id int4 NULL,
                                crm_default_user_id int4 NULL,
                                karma_profile_min int4 NULL,
                                forums_count int4 NULL,
                                salesperson_id int4 NULL,
                                salesteam_id int4 NULL,
                                cart_recovery_mail_template_id int4 NULL,
                                cart_abandoned_delay float8 NULL,
                                shop_ppg int4 NULL,
                                shop_ppr int4 NULL,
                                warehouse_id int4 NULL,
                                CONSTRAINT website_pkey PRIMARY KEY (id)
);

CREATE TABLE public.res_partner (
                                    id serial NOT NULL,
                                    "name" varchar NULL,
                                    company_id int4 NULL,
                                    create_date timestamp NULL,
                                    display_name varchar NULL,
                                    "date" date NULL,
                                    title int4 NULL,
                                    parent_id int4 NULL,
                                    "ref" varchar NULL,
                                    lang varchar NULL,
                                    tz varchar NULL,
                                    user_id int4 NULL,
                                    vat varchar NULL,
                                    website varchar NULL,
                                    "comment" text NULL,
                                    credit_limit float8 NULL,
                                    active bool NULL,
                                    employee bool NULL,
                                    "function" varchar NULL,
                                    "type" varchar NULL,
                                    street varchar NULL,
                                    street2 varchar NULL,
                                    zip varchar NULL,
                                    city varchar NULL,
                                    state_id int4 NULL,
                                    country_id int4 NULL,
                                    partner_latitude numeric NULL,
                                    partner_longitude numeric NULL,
                                    email varchar NULL,
                                    phone varchar NULL,
                                    mobile varchar NULL,
                                    is_company bool NULL,
                                    industry_id int4 NULL,
                                    color int4 NULL,
                                    partner_share bool NULL,
                                    commercial_partner_id int4 NULL,
                                    commercial_company_name varchar NULL,
                                    company_name varchar NULL,
                                    create_uid int4 NULL,
                                    write_uid int4 NULL,
                                    write_date timestamp NULL,
                                    message_main_attachment_id int4 NULL,
                                    email_normalized varchar NULL,
                                    message_bounce int4 NULL,
                                    contact_address_complete varchar NULL,
                                    signup_token varchar NULL,
                                    signup_type varchar NULL,
                                    signup_expiration timestamp NULL,
                                    calendar_last_notif_ack timestamp NULL,
                                    team_id int4 NULL,
                                    ocn_token varchar NULL,
                                    partner_gid int4 NULL,
                                    additional_info varchar NULL,
                                    phone_sanitized varchar NULL,
                                    debit_limit numeric NULL,
                                    last_time_entries_checked timestamp NULL,
                                    invoice_warn varchar NULL,
                                    invoice_warn_msg text NULL,
                                    supplier_rank int4 NULL,
                                    customer_rank int4 NULL,
                                    picking_warn varchar NULL,
                                    picking_warn_msg text NULL,
                                    website_id int4 NULL,
                                    is_published bool NULL,
                                    online_partner_vendor_name varchar NULL,
                                    online_partner_bank_account varchar NULL,
                                    purchase_warn varchar NULL,
                                    purchase_warn_msg text NULL,
                                    website_meta_title varchar NULL,
                                    website_meta_description text NULL,
                                    website_meta_keywords varchar NULL,
                                    website_meta_og_img varchar NULL,
                                    seo_name varchar NULL,
                                    website_description text NULL,
                                    website_short_description text NULL,
                                    online_partner_information varchar NULL,
                                    sale_warn varchar NULL,
                                    sale_warn_msg text NULL,
                                    CONSTRAINT res_partner_check_name CHECK (((((type)::text = 'contact'::text) AND (name IS NOT NULL)) OR ((type)::text <> 'contact'::text))),
	CONSTRAINT res_partner_pkey PRIMARY KEY (id),
	CONSTRAINT res_partner_website_id_fkey FOREIGN KEY (website_id) REFERENCES website(id) ON DELETE RESTRICT
);

CREATE TABLE public.ir_sequence (
                                    id serial NOT NULL,
                                    "name" varchar NOT NULL,
                                    code varchar NULL,
                                    "implementation" varchar NOT NULL,
                                    active bool NULL,
                                    prefix varchar NULL,
                                    suffix varchar NULL,
                                    number_next int4 NOT NULL,
                                    number_increment int4 NOT NULL,
                                    padding int4 NOT NULL,
                                    company_id int4 NULL,
                                    use_date_range bool NULL,
                                    create_uid int4 NULL,
                                    create_date timestamp NULL,
                                    write_uid int4 NULL,
                                    write_date timestamp NULL,
                                    CONSTRAINT ir_sequence_pkey PRIMARY KEY (id)
);

CREATE TABLE public.approval_category (
                                          id serial NOT NULL,
                                          "name" varchar NOT NULL,
                                          company_id int4 NOT NULL,
                                          active bool NULL,
                                          "sequence" int4 NULL,
                                          description varchar NULL,
                                          has_date varchar NOT NULL,
                                          has_period varchar NOT NULL,
                                          has_quantity varchar NOT NULL,
                                          has_amount varchar NOT NULL,
                                          has_reference varchar NOT NULL,
                                          has_partner varchar NOT NULL,
                                          has_payment_method varchar NOT NULL,
                                          has_location varchar NOT NULL,
                                          has_product varchar NOT NULL,
                                          requirer_document varchar NOT NULL,
                                          approval_minimum int4 NOT NULL,
                                          approval_type varchar NULL,
                                          is_manager_approver bool NULL,
                                          automated_sequence bool NULL,
                                          sequence_code varchar NULL,
                                          sequence_id int4 NULL,
                                          create_uid int4 NULL,
                                          create_date timestamp NULL,
                                          write_uid int4 NULL,
                                          write_date timestamp NULL,
                                          CONSTRAINT approval_category_pkey PRIMARY KEY (id),
                                          CONSTRAINT approval_category_sequence_id_fkey FOREIGN KEY (sequence_id) REFERENCES ir_sequence(id) ON DELETE SET NULL
);